server:
  addr: ":8080"
  mode: "debug"  # debug/release

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123456"
  database: "subscribe_demo"
  max_idle_conns: 10
  max_open_conns: 100

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  pool_size: 100

feishu:
  app_id: "cli_xxxxx"        # 飞书应用 App ID
  app_secret: "xxxxx"        # 飞书应用 App Secret
  verification_token: "xxxxx" # 飞书事件订阅 Verification Token
  encrypt_key: "xxxxx"       # 飞书事件订阅加密 Key